# Generated by Django 4.1.3 on 2023-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='profile_pics'),
        ),
    ]
